### ISSUE TITLE
Storing arrays?

### ISSUE THREAD

**Issue by lcpriest** [jamesarosen/ember-i18n#416] opened 2016-10-26 04:03 UTC
ember-pikaday allows translation and it currently does not work well with ember-i18n. I'm currently working on a fork that should get a basic implementation working.

https://github.com/advocately/ember-pikaday-ember-i18n

One of the lookups by ember-pikaday is `this.get('i18n').t('months')` and the return value should be:

```
['January','February','March','April','May','June','July','August','September','October','November','December']
```

Is there any way to store an array in ember-i18n? My current work around is to store it as a comma separated string and `split(')` on the response.

**Comment by jamesarosen** [comment] 2016-10-26 16:48
Duplicate of #382.

**Closed by jamesarosen** 2016-10-26 16:48 UTC
