### ISSUE TITLE
Ember.js 1.10 support

### ISSUE THREAD

**Issue by felipehw** [jamesarosen/ember-i18n#193] opened 2015-02-09 19:03 UTC
When i try a project with Ember 1.10 (in Ember CLI 0.1.12) + ember-i18n 2.2.3... i got this error: `TypeError: attrValue is undefined` in the line 7910 of `ember.debug.js` (`attrValue = attrValue.replace(/^['"]/, '').replace(/['"]$/, '');`).

Maybe this error occur because of HTMLBars ...

**Comment by pjmorse** [comment] 2015-02-09 19:58
@felipehw I don't know the answer to your question offhand, but I'd suggest with those relatively new versions of Ember and Ember-CLI you try a newer version of ember-i18n - 2.9.1 or 3.0.0 beta - and see if that makes the problem go away?

**Comment by felipehw** [comment] 2015-02-10 11:53
I try, the problem remains :/ .

**Comment by jamesarosen** [comment] 2015-02-10 19:11
I don't think we have 1.10 compatibility yet, even on the 3.0-beta series. I tried adding a test for it just now and the tests fail with

```
Error: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.`
```

We'll need a way to get `ember-template-compiler.js` into the test suite. The [npm package](https://www.npmjs.com/package/ember-template-compiler) of it won't work because we need to run the compilation in the (headless) browser for the tests.

**Comment by dshrestha** [comment] 2015-02-10 22:18
Here is a quick jsbin : http://emberjs.jsbin.com/cibiteyebe/1/
to demonstrate the issue with localization with beta version 3. The issue seems to be with the helper.

    EmHandlebars.registerBoundHelper('t', function(key, options) {
      return new EmHandlebars.SafeString(I18n.t(key, options.hash));
    });

key is getting passed as undefined. In the jsbin if we remove the {{t user.edit.title}}, the app runs.

**Comment by jamesarosen** [comment] 2015-02-10 22:36
#195 will let us start testing against Ember 1.10. All of the tests pass on Ember 1.10, so whatever is happening hear isn't being exercised in our test suite.

**Comment by jamesarosen** [comment] 2015-02-10 22:37
@dshrestha that JSBin is for Ember-I18n v 2.9 or lower, which is *definitely not* compatible with Ember 1.10. Have you tried Ember-I18n v3.0.0-beta.3?

**Comment by jamesarosen** [comment] 2015-02-10 22:39
@dshrestha additionally, `{{t user.edit.title}}` should be `{{t "user.edit.title"}}`. What you wrote means "look up the translation key at `controller.user.edit.title`. What you actually meant was "the translation key is `'user.edit.title'`."

**Comment by dshrestha** [comment] 2015-02-10 22:43
I am pretty sure I downloaded v3.0.0-beta.3 and pasted the source code there. Oh and I am really sorry for the missing out the quote though, have been staring at code all day - the jsbin now works! Thanks.

**Comment by jamesarosen** [comment] 2015-02-10 22:44
Sorry, I saw `translateAttr` in the i18n source you included and thought we had dropped that in v3.0.0-beta.3. It turns out it'll be dropped in v3.0.0-beta.4. The quotes were the issue!

**Comment by jamesarosen** [comment] 2015-02-10 22:45
@felipehw are you using `translateAttr`?

**Comment by felipehw** [comment] 2015-02-11 12:58
@jamesarosen , yes. I'm using  translateAttr :/.

**Comment by jamesarosen** [comment] 2015-02-11 16:23
Sadly, we weren't able to make that work in Ember 1.9+.

**Comment by felipehw** [comment] 2015-02-11 17:22
@jamesarosen,
the other features of ember-i18n will work with Ember 1.9+?
Maybe i must remove `translateAttr` and  try the v3.0.0-beta.x  because in other way i can't use with Embers + HTMLBars?

**Comment by jamesarosen** [comment] 2015-02-11 17:27
`translateAttr` is the only thing we've removed so far. cf #182

I'll release a beta.4 shortly.

**Comment by jamesarosen** [comment] 2015-02-12 18:06
If you have other problems with 1.10, please feel free to reopen!

**Comment by felipehw** [comment] 2015-02-13 16:11
Thanks, for now ... without problems :D

**Comment by workmanw** [comment] 2015-02-20 03:53
I upgraded to beta.4 and Ember 1.10 and I'm seeing all of my HTMLBars/Handlebars helpers (`{{t}}`) rendering "[object Object]" in place of the string value. This seems to be happening consistently across my app. It seems to be, at some level, due to `Ember.Handlebars.SafeString`. It's that "object" that gets converted into the "[object Object]" string I'm seeing. If I remove the `new EmHandlebars.SafeString` and just return the string value, it works as expected.

I saw a few other related Ember issues, one of which reported by you @jamesarosen, related to this topic and everyone is marked as closed. But I'm still seeing this. Am I doing something wrong? Has anyone else experienced this?

**Comment by jamesarosen** [comment] 2015-02-20 22:57
v3.0.0-beta.4 was [tested against Handlebars 2 and Ember 1.10](https://travis-ci.org/jamesarosen/ember-i18n/builds/50376381), but I haven't tried HTMLbars yet.

**Comment by workmanw** [comment] 2015-02-21 00:09
Oh, Okay. That makes sense then. Thanks!

**Comment by jamesarosen** [comment] 2015-02-21 00:11
I may get a chance to dig in this weekend. You may want to open an issue on
emberjs/ember.js about the regression.

**Comment by jamesarosen** [comment] 2015-02-23 18:32
HTMLbars doesn't have a globals build, so it's hard to test this project against that library. I tried building htmlbars and then including the files suggested by that project's [compile-and-run.html](https://github.com/tildeio/htmlbars/blob/3035edf9f5505e93340273d0cf561c4853e84557/demos/compile-and-run.html#L21-L24):

 * `loader.js`
 * `dom-helper.amd.js`
 * `htmlbars-compiler.amd.js`
 * `htmlbars-runtime.amd.js`

but I get

```
TypeError: 'undefined' is not an object (evaluating 'callback.length')
```

during the library-definition phase.

**Closed** 2015-02-23 18:32 UTC

**Comment by workmanw** [comment] 2015-02-23 19:58
Hmm. So I tried to create a JSBin and it seemed to work okay http://emberjs.jsbin.com/kequfogovo/3/edit . I'm not sure what's going on with our app, but it seems like something else on our side might be causing this issue .... really sorry for the false alarm.

**Comment by sukima** [comment] 2015-05-14 20:18
Was there any resolution to this? Does ember-i18n support HTMLBars? The read me says you need Handlebars. Do you now need both? The conversation thread here shows the issue as closed but no comment as to the resolution of this. Any clarification would be helpful, thanks.

**Comment by jamesarosen** [comment] 2015-05-14 20:22
The tests only run against Handlebars. Nobody has reported any issues with HTMLBars, though.

**Comment by workmanw** [comment] 2015-05-15 00:00
My problem was user error. I had an extra initializer that was inadvertently overriding something inside of Ember-I18n.

My app is working with HTMLBars, Ember 1.10 and Ember-I18n latest.
