### ISSUE TITLE
Ember i18n lazy lookup

### ISSUE THREAD

**Issue by sbounmy** [jamesarosen/ember-i18n#154] opened 2014-10-17 07:09 UTC
Hello,

I found Rails lazy lookup great and looking to implementing it for ember i18n.
Basically when the translation key starts with a dot, it will prefix the key with the template path/name e.g:

``` js
// in templates/users/new.hbs
{{t ('.title') }} // will lookup users.new.title
Sign up!
// in templates/users/_form.hbs
{{t ('.password.label') }} // will lookup users._form.password.label
Enter your password

// Our i18n would look like :
Ember.I18n.translations = {
  users: {
    new: {
      title: 'Sign up!'
    },
    _form: {
     password: {
       label: 'Enter your password'
     }
   }
  }
}
```

Any guideline on how I could fetch the template name/path where I am calling `{{ t 'my_key'}}` translation helper ?
Note I'm using ember-cli and es6 transpiler

**Comment by jamesarosen** [comment] 2015-07-01 14:56
Do you want to try this again on v4.0.0?

**Comment by sbounmy** [comment] 2015-07-01 15:00
I would love to, I have a working prototype on my app however I've found myself monkey patching ember-i18n to make it work.
@jamesarosen which version of ```ember``` is ```ember-i18n``` running against ? I'm still stuck at 1.8.X because of ```ember-easyform```atm

**Comment by jamesarosen** [comment] 2015-07-01 15:09
The [wiki](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Installation#note) suggests you should be on Ember-I18n v3.x.

**Comment by cibernox** [comment] 2015-07-14 10:04
About this topic, I found it very interesting, specially in the context of translating error messages in forms.

That's why if first made this PR #230 to ember-i18n (released in v4.1.0) to enable me to build some mechanism to translate my errors in the context of the current route with an addon https://github.com/cibernox/ember-i18n-errors

This although my addon is focused in errors, this pattern of fallbacks based in the route hierarchy is useful in any context, and ember-i18n can eventually embrace it and absorb my addon.

In my mind the ideal syntax for "route-scoped" translations could be just implicitly do it for those keys starting with a dot, like rails-i18n does.  

That way while `{{t 'some.trans.lation'}}` is an absolute path, `{{t '.trans.lation'}}` is a relative path to the current route.

Being the current route name `parent.child.grandchild`, the relative path would try to find the better translation following this fallback chain:

```rb
parent.child.grandchild.trans.lation
parent.child.trans.lation
parent.trans.lation
trans.lation # or maybe application.trans.lation because the top-level route is the Application route.
```

**Comment by jamesarosen** [comment] 2015-07-18 19:44
I like @cibernox's suggestion to use the route name. It feels much more Ember-ey to me. And it works well with the new [Fallback Keys](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text#fallback-keys) support. It even works pretty well for addons that want to let you override some text in different ways in different parts of your app:

```js
i18n.t('.pagination.next', { default: [ 'my-addon.pagination.next' ] })
```

How does Rails resolve the ordering of the two different kinds of fallbacks in that call?

 1. `route.pagination.next`, `route.my-addon.pagination.next`, `pagination.next`, `my-addon.pagination.next`?
 2. `route.pagination.next`, `pagination.next`, `route.my-addon.pagination.next`, `my-addon.pagination.next`?
 3. something else?

**Comment by cibernox** [comment] 2015-07-19 13:03
For me the ideal behaviour should be (without having looked at what rails does): 

If the translation key is relative (starts with a dot) then the routes take preference, and the provided fallbacks go after that.

Perhaps a more accurate term than is `expandable` keys. If a key (p.e ".free-hugs") starts with a dot it's considered "expandable" and "compiles" to 
```js
[
  'grandeparent-route.parent-route.current-route.free-hugs',
  'grandeparent-route.parent-route.free-hugs',
  'grandeparent-route.free-hugs',
  'free-hugs'
]
```

And any other fallback is applied after them.

However, there is a small quirk in this approach (that haven't bitten me, but i'm aware it's still there):

Lets revive my ascii-art capabilities to explain it.
```js
// translations.js
{
  parent {
    favouritePhrase: "Kids today ....",
    child: {
      favouritePhrase: "Y'know bro?",
    }
  }  
}

```
```hbs
// When in /parent
----------------------------------------------------------------------------------------------------
| {{!-- parent.hbs --}}                                                                            |
| {{t '.favouritePhrase'}} // Translates to "Kids today ...."                                      |
|                                                                                                  |
| {{outlet}}                                                                                       |
|                                                                                                  |
----------------------------------------------------------------------------------------------------

// When you transition to /parent/child and the outlet is rendered
----------------------------------------------------------------------------------------------------
| {{!-- parent.hbs --}}                                                                            |
| {{t '.favouritePhrase'}}    // Still translates to "Kids today ....". Route name is not observed |
|                                                                                                  |
| -----------------------------------------------------------------------------------------------  |
| | {{!-- child.hbs --}}                                                                         | |
| | {{t '.favouritePhrase'}} // Translates to "Y'know bro?"                                      | |
| |                                                                                              | |
| -----------------------------------------------------------------------------------------------  |
|                                                                                                  |
----------------------------------------------------------------------------------------------------

// Now you reload being in /parent/child
----------------------------------------------------------------------------------------------------
| {{!-- parent.hbs --}}                                                                            |
| {{t '.favouritePhrase'}}    // Still translates to "Y'know bro?". Route name is "parent.child"   |
|                                                                                                  |
| -----------------------------------------------------------------------------------------------  |
| | {{!-- child.hbs --}}                                                                         | |
| | {{t '.favouritePhrase'}} // Translates to "Y'know bro?"                                      | |
| |                                                                                              | |
| -----------------------------------------------------------------------------------------------  |
|                                                                                                  |
```

The problem is that when within a given route, the translation in the template of the parent one will still use the translation of the child one when available if the key is the same and the translation is different.
While a bit unlikely, this might bite someone.

I don't know if there is a way of freeze a translations to the route name of the `{{outlet}}` in which it's rendered, regardless of if a more nested route is active. This is the only caveat I see in this approach.

**Comment by cibernox** [comment] 2015-07-19 18:54
@mixonic Can we ask for your insight of how this works in the ember view layer? Is it possible to a helper/component know the outlet in which it's going to be rendered instead of the route name?

**Comment by mixonic** [comment] 2015-07-19 23:33
@cibernox the only way I believe a helper or component could know the route (or possibly sub-route) being entered/rendered would possibly be through the routing service. that service is not public or well-defined yet though, perhaps there is a use case here that informs it.

There has been some discussion about a using the `outlet` keyword to hop to the routable component hosting your component: https://github.com/emberjs/rfcs/issues/78 This may be an applicable use-case for that feature, but in that case it would not be strongly coupled to the route but to some component state.

I strongly suggest trying to design something that works with DDAU today, and we can see what the pressure points it applies to the framework are. Interesting idea, I'll be thinking it over!

**Comment by sbounmy** [comment] 2015-08-24 10:56
hmm AFAIK the current easiest implementation would be using ```controller:application#currentRouteName``` or ```router:main#currentRouteName``` to return the current route e.g ```parent.child```. I believe it wont support @cibernox described approach but its a quick win if we could find a way to inject / fetch this  ```currentRouteName``` in Ember I18n ```t``` helper.

**Comment by mixonic** [comment] 2015-08-24 11:34
@sbounmy if you use the `Ember.Helper.extend` version of a helper definition, you can `Ember.inject.controller('application')`

**Comment by sbounmy** [comment] 2015-08-24 11:50
@mixonic Yes, I've tried but "Defining an injected controller property on a non-controller is not allowed." error is raised :(

There is currently no way to inject something into a helper e.g:
```
application.inject('helper:t', 'application', 'controller:application') // not supported
```

**Comment by mixonic** [comment] 2015-08-24 11:52
Ah yeah, `Ember.inject.controller` has a validation. I don't see why `application.inject` in an `initializer` would fail though. Can you provide a JSBin?

**Comment by cibernox** [comment] 2015-08-24 12:01
Regardless of the technical details of how have access to the `currentRouteName` the fact that makes me resilent of implementhing this is the one I exposed [a few messages up](https://github.com/jamesarosen/ember-i18n/issues/154#issuecomment-122660063).

If a "relative" translation is in a parent outlet, the translation may differ depending on if you transition to the child route from the parent one or you reach that route directly. I get that the changes are small, but is a nasty edge case I'd rather not have. Feels inconsistent.

**Comment by sbounmy** [comment] 2015-08-24 12:37
@mixonic as ember + jsbin seems broken I've setup a quick twiddle http://ember-twiddle.com/b5cb246f24f45ddfb55d this is backed by this ticket https://github.com/emberjs/ember.js/issues/11021

@cibernox you're definitely right, might want to find another workaround until emberjs/rfcs#78

**Comment by mixonic** [comment] 2015-08-24 13:26
@sbounmy there were some issues with that Twiddle. Injection of a controller onto a helper works fine in http://ember-twiddle.com/0141c59e45a15eec8ff5

You used `register` instead of `inject` most notably.

**Comment by GCorbel** [comment] 2016-09-01 19:29
Is there any update on the subject. I have the same problem.

**Comment by sandstrom** [comment] 2017-10-27 10:32
There is now a router service we could use (since Ember 2.15).

https://github.com/emberjs/ember.js/pull/14805/files#diff-19d10596bb077873e825b9abe0f5fb71R22

**Comment by jamesarosen** [comment] 2018-10-23 23:51
jamesarosen/ember-i18n has been deprecated in favor of [ember-intl](https://github.com/ember-intl).

**Closed by jamesarosen** 2018-10-23 23:51 UTC
