### ISSUE TITLE
t helper not registered

### ISSUE THREAD

**Issue by lil25** [jamesarosen/ember-i18n#295] opened 2015-08-20 06:32 UTC
Hello

I was trying to migrate from ember cli i18n to ember i18n, but I met some problem. For some reason 't' helper didn't register for using in templates.
Are there any way to set up 't' helper manually?

I use Ember 1.13 and Ember-CLI 1.13.6

Thanks in advance.

**Comment by jamesarosen** [comment] 2015-08-20 16:47
What version of Ember-I18n? In 4.1.1, we manually registered the helper. In 4.1.2, we started relying on the auto-lookup for compatibility with Ember 2.1. If you're on 4.1.2 and it's not working, try 4.1.1 and let me know.

**Comment by krivaten** [comment] 2015-08-20 20:22
Was having the same problem. Downgraded to 4.1.1 and it worked. Cheers! :beers:

**Comment by jamesarosen** [comment] 2015-08-20 20:22
@rwjblue :(

**Comment by rwjblue** [comment] 2015-08-21 01:27
What is the easiest way for be to reproduce/test this?

**Comment by lil25** [comment] 2015-08-21 06:16
For 4.1.1 version I have error with 't' helper, when I updated to 4.1.2 't' helper started to work, but there was a problem with default locale, I couldn't set it neither in config nor in initializer. But I managed to do it in application route on beforeModel hook this.set('i18n.locale', ENV.i18n.defaultLocale);

So for me this issue is resolved.
Also I'm using Mocha instead of qUnit, maybe that was the reason, i'm not able to check now.

**Comment by corrspt** [comment] 2015-08-25 19:55
For my situation I'm using a new ember project (ember 2.0, ember cli 1.13.8 with a few addons such as ember-model-validator and ember-i18n) and it happens to me (with 4.1.2, the problem does not occur with 4.1.1) the same error when having this template:

```html
{{bs-attribute type='text' label=(t 'model.entity.name.label') title='Title' value=model.name helpText='helpMe' }}
```

This bs-attribute is just a simple component I made 

```html
<div class="form-group {{if hasError 'has-error'}}">
  <label title="{{title}}">{{label}}</label>
  {{input type=type class='form-control' placeholder=placeholder value=value}}
  {{#if hasError}}
    {{#each errors as |error|}}
      <span class="help-block">{{error.message}}</span>
    {{/each}}
  {{else}}
    {{#if hasHelp}}
      <span class="help-block">{{helpText}}</span>
    {{/if}}
  {{/if}}
</div>
````

With the following JS

```javascript
import Ember from 'ember';

export default Ember.Component.extend({

  helpText: '',
  hasHelp: Ember.computed.notEmpty('helpText'),
  errors: '',
  hasError: Ember.computed.notEmpty('errors')
});
```

@rwjblue I was trying to create a project to reproduce the issue but I'm facing an error when doing ember new my-new-app. I'll have to debug it further. Doesn't make much sense, I didn't upgrade anything (no new ember or ember-cli version) since I created the previous project (where the error occurs)
```
git rev-list -n1 broccoli-peristent-filter: fatal: ambiguous argument 'broccoli-peristent-filter': unknown revision or path not in the working tree.
```
Not quite sure where the "peristent-filter" comes from (and it's weird, should be broccoli-persistent-filter). I don't see it in my package.json. Must be a dependency from some other thing.

**Comment by jamesarosen** [comment] 2015-09-04 02:06
Closing. If anyone can enumerate reproduction steps, I'll gladly take a look.

**Closed by jamesarosen** 2015-09-04 02:06 UTC
